name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull hoangnv99/teamfab-frontend-2:latest
    - name: Delete Old docker container
      run: sudo docker rm -f hoangnv99/teamfab-frontend-2 || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name teamfab-frontend-2 hoangnv99/teamfab-frontend-2